# Feature Scaling

In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import MinMaxScaler, StandardScaler

# Example dataset
numeric_data = pd.DataFrame({
    'Salary':[30000,45000,60000,80000,120000],
    'AGE': [25,32,47,51,62]
})
numeric_data

   Salary  AGE
0   30000   25
1   45000   32
2   60000   47
3   80000   51
4  120000   62

### Standard Scaling (Z-score)

In [6]:
std_scaler = StandardScaler()
scaled_std = std_scaler.fit_transform(numeric_data)
df = pd.DataFrame(scaled_std,columns=numeric_data.columns)
print('\n Standard Scaling :\n',df)

 Standard Scaling :
      Salary       AGE
0 -1.184341 -1.382872
1 -0.704203 -0.856780
2 -0.224065  0.270562
3  0.416120  0.571186
4  1.696489  1.397904

 fit_transform():  does two stepsat ones:
- fit(): Learns the mean and standard deviation of data
- transform() : Applys the Scaling(converts data to Z-scores)
(For StandardScaler: Each Feature becomes mean=0 and std=1)

### MinMax Scaling (0-1)

In [8]:
minmax_scaler = MinMaxScaler()
scaled_minmax = minmax_scaler.fit_transform(numeric_data)
print('\nMinMax  Scaling :\n',pd.DataFrame(scaled_minmax,columns=numeric_data.columns))

MinMax  Scaling :
      Salary       AGE
0  0.000000  0.000000
1  0.166667  0.189189
2  0.333333  0.594595
3  0.555556  0.702703
4  1.000000  1.000000

Xscaled = (X - Xmin)/(Xmax - Xmin)
1st Value = (25-25)/(62-25) = 0
12nd Value = (32-25)/(62-32) = 0.18...

# Encoding Categorical Variables

## Converts text labels to numeric format for ML models

In [14]:
from sklearn.preprocessing import LabelEncoder,OneHotEncoder

# Sample data
cat_data = pd.DataFrame({
    'Department': ['HR','Sales','IT','HR','IT','Finance']
})
cat_data

  Department
0         HR
1      Sales
2         IT
3         HR
4         IT
5    Finance

### Label Encoding

In [15]:
label_encoder = LabelEncoder()
cat_data['Dept_label']=label_encoder.fit_transform(cat_data.Department)
print("Label Encoded:\n",cat_data)

Label Encoded:
   Department  Dept_label
0         HR           1
1      Sales           3
2         IT           2
3         HR           1
4         IT           2
5    Finance           0

### OneHot Encoding

In [16]:
cat_data_ohe = pd.get_dummies(cat_data.Department,prefix='Dept')
print('OneHot Encoded: \n',cat_data_ohe)

OneHot Encoded:
    Dept_Finance  Dept_HR  Dept_IT  Dept_Sales
0         False     True    False       False
1         False    False    False        True
2         False    False     True       False
3         False     True    False       False
4         False    False     True       False
5          True    False    False       False

# Normalization

In [19]:
from sklearn.preprocessing import Normalizer

# Sample data
array= np.array([[3.0,4.0],[1.0,0.0],[0.0,8.0]])
print('Original data:\n',array)

Original data:
 [[3. 4.]
 [1. 0.]
 [0. 8.]]

In [20]:
normalizer =Normalizer()
normalized_data = normalizer.fit_transform(array)
print('Normalized Data:\n',normalized_data)

Normalized Data:
 [[0.6 0.8]
 [1.  0. ]
 [0.  1. ]]

For each row,the Normalizer: Computer the Euclidean norm (magnitude):
norm = sqrt(x1^2 + x2^2 + ...)

Divides Each Element by norm:
x1_normalized = x1/norm

Calculate Row norm: For[3,4] --> norm = sqrt(3^2 + 4^2) = 5
Divides each element by Norm: [3/5,4/5] = [0.6,0.8] (now has length 1)